# ローカルでのテスト自動化
version: '3.8'
services:
  
  builder:
    build:
      context: ../
      dockerfile: ./container/test/Dockerfile
      target: test_builder
    image: fit_test_builder

  runner:
    build:
      context: ../
      dockerfile: ./container/test/Dockerfile
      target: test_runner
    image: fit_test_runner
    init: true