# テスト用のコンテナ
version: '3.8'
services:

# テスト用の git リポジトリを保持する docker image の作成
  test-builder:
    build:
      context: ../
      dockerfile: ./container/test/Dockerfile
      target: test_builder
    image: fit_test_builder

# node によるテスト実行
  test-runner:
    build:
      context: ../
      dockerfile: ./container/test/Dockerfile
      target: test_runner
    image: fit_test_runner
    init: true