# 手動実行による vscode extension デプロイのワークフロー

name: Manual workflow

# 手動実行でのワークフロー実行
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      deploy:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'update version number (major, minor, patch)'
        # Default value if no value is explicitly provided
        default: 'patch'
        # Input has to be provided for the workflow to run
        required: true


jobs:
  # npm version での更新、vsix のデプロイ、を行う
  deploy:
    runs-on: ubuntu-latest
    steps:
    # npm version での更新
    - name: setup checkout
      uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v2
    - name: setup push
      uses: actions-js/push@v1.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: npm version up
      run: |
        git checkout main
        npm version ${{ github.event.inputs.deploy }}
        git push origin main
        git push origin --tags
    # vsix のビルド
    - name: build vsix
      run: |
        npm ci
        npm install --global vsce
        vsce package
    # vsix のパスを環境変数に登録
    - name: set vsix path to env
      run: echo '::set-output name=VSIX_PATH::`ls *.vsix`'
      id: vsix-path
    # vsix をアーティファクトとして登録
    - name: upload as artifact
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/${{ steps.vsix-path.outputs.VSIX_PATH }}
    # vsix のデプロイ
    - name: vsce publish for container
      run: |
        vsce publish --pat ${{ VSCE_TOKEN }}
